2022-06-26T16:21:45.8884164-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-06-26T16:21:45.9112879-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-06-26T16:21:45.9115140-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-06-26T16:21:45.9115540-03:00  [INF] Content root path: "C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite" (b5d60022)
2022-06-26T16:40:38.3286984-03:00  [INF] Application is shutting down... (90f52c38)
2022-06-26T16:40:51.0419424-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-06-26T16:40:51.0602202-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-06-26T16:40:51.0603816-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-06-26T16:40:51.0605866-03:00  [INF] Content root path: "C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite" (b5d60022)
2022-06-26T16:40:59.2154708-03:00 0HMINLF5O6N2Q:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2022-06-26T16:40:59.2585542-03:00 0HMINLF5O6N2Q:00000001 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Index (Hotsite)"' (500cc934)
2022-06-26T16:40:59.3577216-03:00 0HMINLF5O6N2Q:00000001 [INF] Route matched with "{action = \"Index\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Index()" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:40:59.3858397-03:00 0HMINLF5O6N2Q:00000001 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:40:59.5167905-03:00 0HMINLF5O6N2Q:00000001 [INF] Executed ViewResult - view "Index" executed in 120.1092ms. (f66409e9)
2022-06-26T16:40:59.5174346-03:00 0HMINLF5O6N2Q:00000001 [INF] Executed action "Hotsite.Controllers.HomeController.Index (Hotsite)" in 158.089ms (afa2e885)
2022-06-26T16:40:59.5264455-03:00 0HMINLF5O6N2Q:00000001 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Index (Hotsite)"' (99874f2b)
2022-06-26T16:40:59.5365777-03:00 0HMINLF5O6N2Q:00000001 [INF] Request finished in 321.4951ms 200 text/html; charset=utf-8 (791a596a)
2022-06-26T16:41:12.4089437-03:00 0HMINLF5O6N2Q:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 46 (ca22a1cb)
2022-06-26T16:41:12.4124261-03:00 0HMINLF5O6N2Q:00000002 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:41:12.4489029-03:00 0HMINLF5O6N2Q:00000002 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:41:17.6817810-03:00 0HMINLF5O6N2Q:00000002 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 5231.7594ms (afa2e885)
2022-06-26T16:41:17.6920841-03:00 0HMINLF5O6N2Q:00000002 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:41:17.9200905-03:00 0HMINLF5O6N2Q:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Hotsite.Models.DatabaseService.CadastraInteresse(Interesse cad) in C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite\Models\DatabaseService.cs:line 15
   at Hotsite.Controllers.HomeController.Cadastrar(Interesse cad) in C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite\Controllers\HomeController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-06-26T16:41:18.1044321-03:00 0HMINLF5O6N2Q:00000002 [INF] Request finished in 5695.8495ms 500 text/html; charset=utf-8 (791a596a)
2022-06-26T16:42:45.7357538-03:00  [INF] Application is shutting down... (90f52c38)
2022-06-26T16:42:56.5308986-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-06-26T16:42:56.5380628-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-06-26T16:42:56.5382320-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-06-26T16:42:56.5382708-03:00  [INF] Content root path: "C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite" (b5d60022)
2022-06-26T16:43:02.7359886-03:00 0HMINLGAI544S:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2022-06-26T16:43:02.7700072-03:00 0HMINLGAI544S:00000001 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Index (Hotsite)"' (500cc934)
2022-06-26T16:43:02.8840421-03:00 0HMINLGAI544S:00000001 [INF] Route matched with "{action = \"Index\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Index()" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:43:02.9203218-03:00 0HMINLGAI544S:00000001 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:43:03.0942362-03:00 0HMINLGAI544S:00000001 [INF] Executed ViewResult - view "Index" executed in 177.9933ms. (f66409e9)
2022-06-26T16:43:03.0947855-03:00 0HMINLGAI544S:00000001 [INF] Executed action "Hotsite.Controllers.HomeController.Index (Hotsite)" in 206.1083ms (afa2e885)
2022-06-26T16:43:03.0956393-03:00 0HMINLGAI544S:00000001 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Index (Hotsite)"' (99874f2b)
2022-06-26T16:43:03.0994858-03:00 0HMINLGAI544S:00000001 [INF] Request finished in 367.5072ms 200 text/html; charset=utf-8 (791a596a)
2022-06-26T16:43:12.7100869-03:00 0HMINLGAI544S:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 40 (ca22a1cb)
2022-06-26T16:43:12.7129798-03:00 0HMINLGAI544S:00000002 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:43:12.7383680-03:00 0HMINLGAI544S:00000002 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:43:17.5526245-03:00 0HMINLGAI544S:00000002 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 4812.9953ms (afa2e885)
2022-06-26T16:43:17.5534705-03:00 0HMINLGAI544S:00000002 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:43:17.6066212-03:00 0HMINLGAI544S:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 442
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Hotsite.Models.DatabaseService.CadastraInteresse(Interesse cad) in C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite\Models\DatabaseService.cs:line 15
   at Hotsite.Controllers.HomeController.Cadastrar(Interesse cad) in C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite\Controllers\HomeController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-06-26T16:43:17.6767403-03:00 0HMINLGAI544S:00000002 [INF] Request finished in 4967.4839ms 500 text/html; charset=utf-8 (791a596a)
2022-06-26T16:43:45.9277589-03:00  [INF] Application is shutting down... (90f52c38)
2022-06-26T16:44:00.4080447-03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2022-06-26T16:44:00.4195931-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2022-06-26T16:44:00.4197765-03:00  [INF] Hosting environment: "Development" (c3307c92)
2022-06-26T16:44:00.4198126-03:00  [INF] Content root path: "C:\Users\flper\Documents\EAD Senac\UC06\projetohotsite" (b5d60022)
2022-06-26T16:44:03.8202165-03:00 0HMINLGSOO03A:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 40 (ca22a1cb)
2022-06-26T16:44:03.8739230-03:00 0HMINLGSOO03A:00000001 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:44:03.9602053-03:00 0HMINLGSOO03A:00000001 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:44:08.8768107-03:00 0HMINLGSOO03A:00000001 [ERR] Erro ao gravar no banco An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call. (30b1b160)
2022-06-26T16:44:08.8958365-03:00 0HMINLGSOO03A:00000001 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:44:09.0596097-03:00 0HMINLGSOO03A:00000001 [INF] Executed ViewResult - view "Index" executed in 141.983ms. (f66409e9)
2022-06-26T16:44:09.0602008-03:00 0HMINLGSOO03A:00000001 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 5099.4646ms (afa2e885)
2022-06-26T16:44:09.0615958-03:00 0HMINLGSOO03A:00000001 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:44:09.0784471-03:00 0HMINLGSOO03A:00000001 [INF] Request finished in 5251.6974ms 200 text/html; charset=utf-8 (791a596a)
2022-06-26T16:44:12.3586016-03:00 0HMINLGSOO03A:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 40 (ca22a1cb)
2022-06-26T16:44:12.3604412-03:00 0HMINLGSOO03A:00000002 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:44:12.3614731-03:00 0HMINLGSOO03A:00000002 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:44:16.4662575-03:00 0HMINLGSOO03A:00000002 [ERR] Erro ao gravar no banco An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call. (30b1b160)
2022-06-26T16:44:16.4678699-03:00 0HMINLGSOO03A:00000002 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:44:16.4738790-03:00 0HMINLGSOO03A:00000002 [INF] Executed ViewResult - view "Index" executed in 6.4015ms. (f66409e9)
2022-06-26T16:44:16.4740233-03:00 0HMINLGSOO03A:00000002 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 4112.3363ms (afa2e885)
2022-06-26T16:44:16.4741424-03:00 0HMINLGSOO03A:00000002 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:44:16.4743541-03:00 0HMINLGSOO03A:00000002 [INF] Request finished in 4116.1333ms 200 text/html; charset=utf-8 (791a596a)
2022-06-26T16:46:17.6709712-03:00 0HMINLGSOO03A:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 40 (ca22a1cb)
2022-06-26T16:46:17.6729837-03:00 0HMINLGSOO03A:00000003 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:46:17.6741406-03:00 0HMINLGSOO03A:00000003 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:46:18.2607362-03:00 0HMINLGSOO03A:00000003 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:46:18.2634370-03:00 0HMINLGSOO03A:00000003 [INF] Executed ViewResult - view "Index" executed in 2.9065ms. (f66409e9)
2022-06-26T16:46:18.2636117-03:00 0HMINLGSOO03A:00000003 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 589.1314ms (afa2e885)
2022-06-26T16:46:18.2637259-03:00 0HMINLGSOO03A:00000003 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:46:18.2639984-03:00 0HMINLGSOO03A:00000003 [INF] Request finished in 594.4171ms 200 text/html; charset=utf-8 (791a596a)
2022-06-26T16:46:31.5773052-03:00 0HMINLGSOO03A:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:5000/Home/Cadastrar application/x-www-form-urlencoded 40 (ca22a1cb)
2022-06-26T16:46:31.5782128-03:00 0HMINLGSOO03A:00000004 [INF] Executing endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (500cc934)
2022-06-26T16:46:31.5793509-03:00 0HMINLGSOO03A:00000004 [INF] Route matched with "{action = \"Cadastrar\", controller = \"Home\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Cadastrar(Hotsite.Models.Interesse)" on controller "Hotsite.Controllers.HomeController" ("Hotsite"). (122b2fdf)
2022-06-26T16:46:31.6833355-03:00 0HMINLGSOO03A:00000004 [INF] Executing ViewResult, running view "Index". (c83d0e25)
2022-06-26T16:46:31.6857762-03:00 0HMINLGSOO03A:00000004 [INF] Executed ViewResult - view "Index" executed in 2.537ms. (f66409e9)
2022-06-26T16:46:31.6859347-03:00 0HMINLGSOO03A:00000004 [INF] Executed action "Hotsite.Controllers.HomeController.Cadastrar (Hotsite)" in 106.3926ms (afa2e885)
2022-06-26T16:46:31.6860484-03:00 0HMINLGSOO03A:00000004 [INF] Executed endpoint '"Hotsite.Controllers.HomeController.Cadastrar (Hotsite)"' (99874f2b)
2022-06-26T16:46:31.6863038-03:00 0HMINLGSOO03A:00000004 [INF] Request finished in 109.3284ms 200 text/html; charset=utf-8 (791a596a)
